name: Continuous Integration - Tests

on: [push, pull_request]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: ./server
        run: npm ci


      - name: Create test DB file
        working-directory: ./server
        run: touch database.sqlite

      - name: Give permission to binaries
        working-directory: ./server
        run: chmod +x node_modules/.bin/* || true

      - name: Run unit tests
        working-directory: ./server
        run: npm test